### ISSUE TITLE
Reproduce the performance in the paper

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/DewarpNet#24]
Hi~, I could not reproduce the performance in the paper using the released code.  

And I guess the reason is that the train and val dataset are different from yours. So could you release the complete meshid "split.txt". 
Besides, what is the pytorch version of the released code.

Thanks a lot !
Best wishes !

**Comment by sagniklp** [comment]
I've recently noticed that performance varies due to the align_corner flag in the interpolate and grid_sample function. Newer PyTorch versions use different default values for the flag. Please check that. We had tried using PyTorch 0.4.1. Could you please describe your current training schedule? How many epochs did you train for each network? What are the BM MSE and WC MSE values after separate training?

I've used the following meshsplit.txt:
[meshsplit.txt](https://github.com/cvlab-stonybrook/DewarpNet/files/5152880/meshsplit.txt)

I've also noticed some of the meshes are missing in the final released data but those meshes are child meshes of mesh 1, which shouldn't cause much difference in performance. I'll release some additional data soon to fix this issue.

**Comment by fh2019ustc** [comment]
Thank you! We have reproduced the performance.
