### ISSUE TITLE
Reproducing Fig. 7 with infer.py

### ISSUE THREAD

**Issue by FloorVerhoeven** [cvlab-stonybrook/DewarpNet#38]
Hi!

I'm trying to reproduce the unwarped images in row 3 of figure 7 in the paper but am not managing.
I'm using the infer.py file as provided in this repo, and have both tried with the models available [here](https://drive.google.com/file/d/1hJKCb4eF1AJih_dhZOJSF5VR-ZtRNaap/view) and [here](https://drive.google.com/drive/folders/1yFiYBIkrY61IuRniiV4MLF3jyrNeVd2I). For pytorch I'm using version 0.4.1. As input images I'm using the 4 images provided in the eval/inp folder.
For example on image 13_2 I get [this result](https://user-images.githubusercontent.com/10435129/154368639-1edd8821-e0a0-4e51-ae18-af0e1c0691ab.png)

Do you have any ideas what I might need to change in order to be able to reproduce the images in Fig. 7 of the paper?

**Comment by sagniklp** [comment]
I believe this is happening due to some error in the shape network regression, it could be related to normalization. Could you please share the output of the shape network?

**Comment by FloorVerhoeven** [comment]
Hi Sagnik,

Sorry for the delay. This is the output from the shape network (for the 13_2 file): 
![Screenshot from 2022-04-01 15-48-02](https://user-images.githubusercontent.com/10435129/161279476-0ac3d386-2d26-40c2-831e-99de1e5af081.png)
and [as .exr file](https://drive.google.com/file/d/1oKx_TmYKkNV0UuMH42zZFCiqp65jjNzf/view?usp=sharing)

**Comment by sagniklp** [comment]
This issue is resolved if you use scipy (<1.2.0) to load the image. I've updated some instructions in the infer.py accordingly. Following is the wc output you should get if you use scipy:

![wc_13_2 copy](https://user-images.githubusercontent.com/10586359/164165497-b49e2ff9-8a78-444e-9e90-3c3a2510e595.png)

I haven't done further digging about the difference between OpenCV and scipy imread. I guess it's documented somewhere.

Thanks for bringing this to my attention!

**Comment by zxy770624739** [comment]
Hello，can you share the code of the output from the shape network？Thank you！
